### ISSUE TITLE
Login without creating a user

### ISSUE THREAD

**Issue by victorhurdugaci** [ekoshkin/teamcity-azure-active-directory#4]
In the configuration page for this plugin there is a checkbox that says if a user should be created or not upon first login.

Maybe my expectation is wrong but I was expecting to be able to login is that checkbox is unchecked. However, if I try to do that, I just get redirected to the login page. I can only login with a new user if that checkbox is checked.

**Comment by ekoshkin** [comment]
This checkbox if unchecked (creating of new user is forbidden) should work as follow:
 - if such a user was registered already somehow - login should be successful on behalf of that user
 - if user is not found - error message should be shown on login page (sms like - authenticated in aad successfully but teamcity user is not found and creation of new user is forbidden)

You was redirected to login page as expected but no error message was displayed. It will be fixed in scope of #1

**Comment by victorhurdugaci** [comment]
Makes sense. Cheers!
